/**
 * 100 universities — two in every US state (California has three).
 * Real identifiers only: IPEDS unit IDs, Wikipedia titles, domains,
 * coordinates, conferences, brand colors. All metrics are fetched live.
 */
export interface UniversityRef {
  id: string;
  name: string;
  shortName: string;
  abbr: string;
  brandColor: string;
  city: string;
  state: string;
  conference: string;
  region: "Midwest" | "South" | "West" | "Northeast";
  scorecardId: number; // IPEDS unit id — 0 = unknown (skipped in Scorecard call)
  wikiTitle: string;
  domain: string;
  lat: number;
  lng: number;
  approxEnrollment: number;
  approxAcceptRate: number;
}

export const UNIVERSITIES: UniversityRef[] = [
  // ── MIDWEST (IA, IL, IN, KS, MI, MN, MO, ND, NE, OH, SD, WI) ───────
  // Iowa
  { id: "iowa", name: "University of Iowa", shortName: "Iowa", abbr: "IOWA", brandColor: "#FFCD00", city: "Iowa City", state: "IA", conference: "Big Ten", region: "Midwest", scorecardId: 153658, wikiTitle: "University of Iowa", domain: "uiowa.edu", lat: 41.6611, lng: -91.5302, approxEnrollment: 31000, approxAcceptRate: 84 },
  { id: "iowastate", name: "Iowa State University", shortName: "Iowa State", abbr: "ISU", brandColor: "#C8102E", city: "Ames", state: "IA", conference: "Big 12", region: "Midwest", scorecardId: 153603, wikiTitle: "Iowa State University", domain: "iastate.edu", lat: 42.0267, lng: -93.6465, approxEnrollment: 30000, approxAcceptRate: 91 },
  // Illinois
  { id: "northwestern", name: "Northwestern University", shortName: "Northwestern", abbr: "NU", brandColor: "#4E2A84", city: "Evanston", state: "IL", conference: "Big Ten", region: "Midwest", scorecardId: 147767, wikiTitle: "Northwestern University", domain: "northwestern.edu", lat: 42.0565, lng: -87.6753, approxEnrollment: 22000, approxAcceptRate: 7 },
  { id: "illinois", name: "University of Illinois Urbana-Champaign", shortName: "Illinois", abbr: "UIUC", brandColor: "#E84A27", city: "Champaign", state: "IL", conference: "Big Ten", region: "Midwest", scorecardId: 145637, wikiTitle: "University of Illinois Urbana-Champaign", domain: "illinois.edu", lat: 40.1020, lng: -88.2272, approxEnrollment: 56000, approxAcceptRate: 45 },
  // Indiana
  { id: "indiana", name: "Indiana University Bloomington", shortName: "Indiana", abbr: "IU", brandColor: "#990000", city: "Bloomington", state: "IN", conference: "Big Ten", region: "Midwest", scorecardId: 151351, wikiTitle: "Indiana University Bloomington", domain: "iu.edu", lat: 39.1661, lng: -86.5266, approxEnrollment: 45000, approxAcceptRate: 80 },
  { id: "purdue", name: "Purdue University", shortName: "Purdue", abbr: "PUR", brandColor: "#CEB888", city: "West Lafayette", state: "IN", conference: "Big Ten", region: "Midwest", scorecardId: 243780, wikiTitle: "Purdue University", domain: "purdue.edu", lat: 40.4237, lng: -86.9212, approxEnrollment: 50000, approxAcceptRate: 53 },
  // Kansas
  { id: "kansas", name: "University of Kansas", shortName: "Kansas", abbr: "KU", brandColor: "#0051BA", city: "Lawrence", state: "KS", conference: "Big 12", region: "Midwest", scorecardId: 155317, wikiTitle: "University of Kansas", domain: "ku.edu", lat: 38.9543, lng: -95.2558, approxEnrollment: 28000, approxAcceptRate: 88 },
  { id: "kstate", name: "Kansas State University", shortName: "K-State", abbr: "KSU", brandColor: "#512888", city: "Manhattan", state: "KS", conference: "Big 12", region: "Midwest", scorecardId: 155399, wikiTitle: "Kansas State University", domain: "k-state.edu", lat: 39.1836, lng: -96.5717, approxEnrollment: 21000, approxAcceptRate: 95 },
  // Michigan
  { id: "michigan", name: "University of Michigan", shortName: "Michigan", abbr: "UM", brandColor: "#00274c", city: "Ann Arbor", state: "MI", conference: "Big Ten", region: "Midwest", scorecardId: 170976, wikiTitle: "University of Michigan", domain: "umich.edu", lat: 42.2784, lng: -83.7348, approxEnrollment: 47000, approxAcceptRate: 18 },
  { id: "michiganstate", name: "Michigan State University", shortName: "Michigan State", abbr: "MSU", brandColor: "#18453B", city: "East Lansing", state: "MI", conference: "Big Ten", region: "Midwest", scorecardId: 171100, wikiTitle: "Michigan State University", domain: "msu.edu", lat: 42.7018, lng: -84.4822, approxEnrollment: 50000, approxAcceptRate: 72 },
  // Minnesota
  { id: "minnesota", name: "University of Minnesota", shortName: "Minnesota", abbr: "MINN", brandColor: "#7A0019", city: "Minneapolis", state: "MN", conference: "Big Ten", region: "Midwest", scorecardId: 174066, wikiTitle: "University of Minnesota", domain: "umn.edu", lat: 44.9740, lng: -93.2277, approxEnrollment: 52000, approxAcceptRate: 75 },
  { id: "stthomas", name: "University of St. Thomas", shortName: "St. Thomas", abbr: "UST", brandColor: "#510C76", city: "Saint Paul", state: "MN", conference: "Summit League", region: "Midwest", scorecardId: 174914, wikiTitle: "University of St. Thomas (Minnesota)", domain: "stthomas.edu", lat: 44.9408, lng: -93.1923, approxEnrollment: 10000, approxAcceptRate: 85 },
  // Missouri
  { id: "missouri", name: "University of Missouri", shortName: "Mizzou", abbr: "MIZ", brandColor: "#F1B82D", city: "Columbia", state: "MO", conference: "SEC", region: "Midwest", scorecardId: 178396, wikiTitle: "University of Missouri", domain: "missouri.edu", lat: 38.9404, lng: -92.3277, approxEnrollment: 32000, approxAcceptRate: 82 },
  { id: "mostate", name: "Missouri State University", shortName: "Missouri State", abbr: "MOST", brandColor: "#5F0000", city: "Springfield", state: "MO", conference: "Missouri Valley", region: "Midwest", scorecardId: 179566, wikiTitle: "Missouri State University", domain: "missouristate.edu", lat: 37.2034, lng: -93.2837, approxEnrollment: 24000, approxAcceptRate: 83 },
  // North Dakota
  { id: "northdakota", name: "University of North Dakota", shortName: "North Dakota", abbr: "UND", brandColor: "#009A44", city: "Grand Forks", state: "ND", conference: "Summit League", region: "Midwest", scorecardId: 200280, wikiTitle: "University of North Dakota", domain: "und.edu", lat: 47.9234, lng: -97.0787, approxEnrollment: 14000, approxAcceptRate: 83 },
  { id: "ndsu", name: "North Dakota State University", shortName: "NDSU", abbr: "NDSU", brandColor: "#006633", city: "Fargo", state: "ND", conference: "Summit League", region: "Midwest", scorecardId: 200332, wikiTitle: "North Dakota State University", domain: "ndsu.edu", lat: 46.8963, lng: -96.8019, approxEnrollment: 13000, approxAcceptRate: 92 },
  // Nebraska
  { id: "nebraska", name: "University of Nebraska–Lincoln", shortName: "Nebraska", abbr: "NEB", brandColor: "#D00000", city: "Lincoln", state: "NE", conference: "Big Ten", region: "Midwest", scorecardId: 181464, wikiTitle: "University of Nebraska–Lincoln", domain: "unl.edu", lat: 40.8202, lng: -96.7005, approxEnrollment: 25000, approxAcceptRate: 63 },
  { id: "creighton", name: "Creighton University", shortName: "Creighton", abbr: "CU", brandColor: "#005CA9", city: "Omaha", state: "NE", conference: "Big East", region: "Midwest", scorecardId: 181002, wikiTitle: "Creighton University", domain: "creighton.edu", lat: 41.2565, lng: -95.9370, approxEnrollment: 9000, approxAcceptRate: 75 },
  // Ohio
  { id: "ohiostate", name: "Ohio State University", shortName: "Ohio State", abbr: "OSU", brandColor: "#bb0000", city: "Columbus", state: "OH", conference: "Big Ten", region: "Midwest", scorecardId: 204796, wikiTitle: "Ohio State University", domain: "osu.edu", lat: 39.9998, lng: -83.0075, approxEnrollment: 61000, approxAcceptRate: 53 },
  { id: "cincinnati", name: "University of Cincinnati", shortName: "Cincinnati", abbr: "UC", brandColor: "#E00122", city: "Cincinnati", state: "OH", conference: "Big 12", region: "Midwest", scorecardId: 201885, wikiTitle: "University of Cincinnati", domain: "uc.edu", lat: 39.1329, lng: -84.5150, approxEnrollment: 47000, approxAcceptRate: 78 },
  // South Dakota
  { id: "sdsu", name: "South Dakota State University", shortName: "South Dakota State", abbr: "SDSU", brandColor: "#0033A0", city: "Brookings", state: "SD", conference: "Summit League", region: "Midwest", scorecardId: 219471, wikiTitle: "South Dakota State University", domain: "sdstate.edu", lat: 44.3114, lng: -96.7984, approxEnrollment: 12000, approxAcceptRate: 92 },
  { id: "southdakota", name: "University of South Dakota", shortName: "South Dakota", abbr: "USD", brandColor: "#CD1241", city: "Vermillion", state: "SD", conference: "Summit League", region: "Midwest", scorecardId: 219602, wikiTitle: "University of South Dakota", domain: "usd.edu", lat: 42.7843, lng: -96.9289, approxEnrollment: 10000, approxAcceptRate: 87 },
  // Wisconsin
  { id: "wisconsin", name: "University of Wisconsin–Madison", shortName: "Wisconsin", abbr: "UW", brandColor: "#c5050c", city: "Madison", state: "WI", conference: "Big Ten", region: "Midwest", scorecardId: 240444, wikiTitle: "University of Wisconsin–Madison", domain: "wisc.edu", lat: 43.0754, lng: -89.4041, approxEnrollment: 49000, approxAcceptRate: 49 },
  { id: "marquette", name: "Marquette University", shortName: "Marquette", abbr: "MU", brandColor: "#003366", city: "Milwaukee", state: "WI", conference: "Big East", region: "Midwest", scorecardId: 239105, wikiTitle: "Marquette University", domain: "marquette.edu", lat: 43.0389, lng: -87.9293, approxEnrollment: 12000, approxAcceptRate: 82 },

  // ── SOUTH (AL, AR, FL, GA, KY, LA, MS, NC, OK, SC, TN, TX, VA, WV) ──
  // Alabama
  { id: "alabama", name: "University of Alabama", shortName: "Alabama", abbr: "BAMA", brandColor: "#9e1b32", city: "Tuscaloosa", state: "AL", conference: "SEC", region: "South", scorecardId: 100751, wikiTitle: "University of Alabama", domain: "ua.edu", lat: 33.2119, lng: -87.546, approxEnrollment: 38000, approxAcceptRate: 80 },
  { id: "auburn", name: "Auburn University", shortName: "Auburn", abbr: "AU", brandColor: "#0C2340", city: "Auburn", state: "AL", conference: "SEC", region: "South", scorecardId: 100858, wikiTitle: "Auburn University", domain: "auburn.edu", lat: 32.5999, lng: -85.4808, approxEnrollment: 32000, approxAcceptRate: 44 },
  // Arkansas
  { id: "arkansas", name: "University of Arkansas", shortName: "Arkansas", abbr: "ARK", brandColor: "#9D2235", city: "Fayetteville", state: "AR", conference: "SEC", region: "South", scorecardId: 106397, wikiTitle: "University of Arkansas", domain: "uark.edu", lat: 36.0679, lng: -94.1737, approxEnrollment: 30000, approxAcceptRate: 76 },
  { id: "arkstate", name: "Arkansas State University", shortName: "Arkansas State", abbr: "ARST", brandColor: "#CC092F", city: "Jonesboro", state: "AR", conference: "Sun Belt", region: "South", scorecardId: 106245, wikiTitle: "Arkansas State University", domain: "astate.edu", lat: 35.8426, lng: -90.6723, approxEnrollment: 14000, approxAcceptRate: 70 },
  // Florida
  { id: "florida", name: "University of Florida", shortName: "Florida", abbr: "UF", brandColor: "#0021a5", city: "Gainesville", state: "FL", conference: "SEC", region: "South", scorecardId: 134130, wikiTitle: "University of Florida", domain: "ufl.edu", lat: 29.6436, lng: -82.3549, approxEnrollment: 55000, approxAcceptRate: 23 },
  { id: "fsu", name: "Florida State University", shortName: "Florida State", abbr: "FSU", brandColor: "#782f40", city: "Tallahassee", state: "FL", conference: "ACC", region: "South", scorecardId: 134097, wikiTitle: "Florida State University", domain: "fsu.edu", lat: 30.4431, lng: -84.2951, approxEnrollment: 45000, approxAcceptRate: 25 },
  { id: "usf", name: "University of South Florida", shortName: "South Florida", abbr: "USF", brandColor: "#006747", city: "Tampa", state: "FL", conference: "AAC", region: "South", scorecardId: 137351, wikiTitle: "University of South Florida", domain: "usf.edu", lat: 28.0587, lng: -82.4139, approxEnrollment: 50000, approxAcceptRate: 43 },
  { id: "miami", name: "University of Miami", shortName: "Miami", abbr: "MIAMI", brandColor: "#F47321", city: "Miami", state: "FL", conference: "ACC", region: "South", scorecardId: 135726, wikiTitle: "University of Miami", domain: "miami.edu", lat: 25.7182, lng: -80.2793, approxEnrollment: 19000, approxAcceptRate: 19 },
  // Georgia
  { id: "georgia", name: "University of Georgia", shortName: "Georgia", abbr: "UGA", brandColor: "#ba0c2f", city: "Athens", state: "GA", conference: "SEC", region: "South", scorecardId: 139959, wikiTitle: "University of Georgia", domain: "uga.edu", lat: 33.948, lng: -83.3773, approxEnrollment: 40000, approxAcceptRate: 43 },
  { id: "gatech", name: "Georgia Institute of Technology", shortName: "Georgia Tech", abbr: "GT", brandColor: "#B3A369", city: "Atlanta", state: "GA", conference: "ACC", region: "South", scorecardId: 139755, wikiTitle: "Georgia Institute of Technology", domain: "gatech.edu", lat: 33.7756, lng: -84.3963, approxEnrollment: 44000, approxAcceptRate: 17 },
  // Kentucky
  { id: "kentucky", name: "University of Kentucky", shortName: "Kentucky", abbr: "UK", brandColor: "#0033A0", city: "Lexington", state: "KY", conference: "SEC", region: "South", scorecardId: 157085, wikiTitle: "University of Kentucky", domain: "uky.edu", lat: 38.0342, lng: -84.5031, approxEnrollment: 31000, approxAcceptRate: 90 },
  { id: "louisville", name: "University of Louisville", shortName: "Louisville", abbr: "UL", brandColor: "#AD0000", city: "Louisville", state: "KY", conference: "ACC", region: "South", scorecardId: 157289, wikiTitle: "University of Louisville", domain: "louisville.edu", lat: 38.2115, lng: -85.7588, approxEnrollment: 22000, approxAcceptRate: 75 },
  // Louisiana
  { id: "lsu", name: "Louisiana State University", shortName: "LSU", abbr: "LSU", brandColor: "#461D7C", city: "Baton Rouge", state: "LA", conference: "SEC", region: "South", scorecardId: 159391, wikiTitle: "Louisiana State University", domain: "lsu.edu", lat: 30.4133, lng: -91.1800, approxEnrollment: 36000, approxAcceptRate: 76 },
  { id: "tulane", name: "Tulane University", shortName: "Tulane", abbr: "TU", brandColor: "#006747", city: "New Orleans", state: "LA", conference: "AAC", region: "South", scorecardId: 160755, wikiTitle: "Tulane University", domain: "tulane.edu", lat: 29.9402, lng: -90.1212, approxEnrollment: 14000, approxAcceptRate: 11 },
  // Mississippi
  { id: "olemiss", name: "University of Mississippi", shortName: "Ole Miss", abbr: "MISS", brandColor: "#CE1126", city: "Oxford", state: "MS", conference: "SEC", region: "South", scorecardId: 176017, wikiTitle: "University of Mississippi", domain: "olemiss.edu", lat: 34.3652, lng: -89.5364, approxEnrollment: 24000, approxAcceptRate: 62 },
  { id: "msstate", name: "Mississippi State University", shortName: "Mississippi State", abbr: "MSST", brandColor: "#660000", city: "Starkville", state: "MS", conference: "SEC", region: "South", scorecardId: 176080, wikiTitle: "Mississippi State University", domain: "msstate.edu", lat: 33.4505, lng: -88.8184, approxEnrollment: 23000, approxAcceptRate: 54 },
  { id: "jacksonstate", name: "Jackson State University", shortName: "Jackson State", abbr: "JSU", brandColor: "#003DA5", city: "Jackson", state: "MS", conference: "SWAC", region: "South", scorecardId: 176017, wikiTitle: "Jackson State University", domain: "jsums.edu", lat: 32.2988, lng: -90.2116, approxEnrollment: 7000, approxAcceptRate: 67 },
  // North Carolina
  { id: "unc", name: "University of North Carolina at Chapel Hill", shortName: "UNC", abbr: "UNC", brandColor: "#4B9CD3", city: "Chapel Hill", state: "NC", conference: "ACC", region: "South", scorecardId: 199120, wikiTitle: "University of North Carolina at Chapel Hill", domain: "unc.edu", lat: 35.9049, lng: -79.0469, approxEnrollment: 31000, approxAcceptRate: 17 },
  { id: "ncstate", name: "North Carolina State University", shortName: "NC State", abbr: "NCSU", brandColor: "#CC0000", city: "Raleigh", state: "NC", conference: "ACC", region: "South", scorecardId: 199193, wikiTitle: "North Carolina State University", domain: "ncsu.edu", lat: 35.7872, lng: -78.6705, approxEnrollment: 37000, approxAcceptRate: 47 },
  // Oklahoma
  { id: "oklahoma", name: "University of Oklahoma", shortName: "Oklahoma", abbr: "OU", brandColor: "#841617", city: "Norman", state: "OK", conference: "SEC", region: "South", scorecardId: 207500, wikiTitle: "University of Oklahoma", domain: "ou.edu", lat: 35.2058, lng: -97.4457, approxEnrollment: 32000, approxAcceptRate: 71 },
  { id: "okstate", name: "Oklahoma State University", shortName: "Oklahoma State", abbr: "OKST", brandColor: "#FF6600", city: "Stillwater", state: "OK", conference: "Big 12", region: "South", scorecardId: 207388, wikiTitle: "Oklahoma State University", domain: "okstate.edu", lat: 36.1209, lng: -97.0688, approxEnrollment: 25000, approxAcceptRate: 73 },
  // South Carolina
  { id: "southcarolina", name: "University of South Carolina", shortName: "South Carolina", abbr: "SC", brandColor: "#73000A", city: "Columbia", state: "SC", conference: "SEC", region: "South", scorecardId: 218663, wikiTitle: "University of South Carolina", domain: "sc.edu", lat: 33.9940, lng: -81.0299, approxEnrollment: 35000, approxAcceptRate: 64 },
  { id: "clemson", name: "Clemson University", shortName: "Clemson", abbr: "CLEM", brandColor: "#F56600", city: "Clemson", state: "SC", conference: "ACC", region: "South", scorecardId: 217882, wikiTitle: "Clemson University", domain: "clemson.edu", lat: 34.6834, lng: -82.8374, approxEnrollment: 28000, approxAcceptRate: 43 },
  { id: "coastalcarolina", name: "Coastal Carolina University", shortName: "Coastal Carolina", abbr: "CCU", brandColor: "#006F71", city: "Conway", state: "SC", conference: "Sun Belt", region: "South", scorecardId: 218070, wikiTitle: "Coastal Carolina University", domain: "coastal.edu", lat: 33.7932, lng: -79.0187, approxEnrollment: 10000, approxAcceptRate: 70 },
  // Tennessee
  { id: "tennessee", name: "University of Tennessee", shortName: "Tennessee", abbr: "VOLS", brandColor: "#FF8200", city: "Knoxville", state: "TN", conference: "SEC", region: "South", scorecardId: 221759, wikiTitle: "University of Tennessee", domain: "utk.edu", lat: 35.9544, lng: -83.9295, approxEnrollment: 35000, approxAcceptRate: 75 },
  { id: "vanderbilt", name: "Vanderbilt University", shortName: "Vanderbilt", abbr: "VANDY", brandColor: "#866D4B", city: "Nashville", state: "TN", conference: "SEC", region: "South", scorecardId: 221999, wikiTitle: "Vanderbilt University", domain: "vanderbilt.edu", lat: 36.1447, lng: -86.8027, approxEnrollment: 14000, approxAcceptRate: 5 },
  // Texas
  { id: "texas", name: "University of Texas at Austin", shortName: "Texas", abbr: "UT", brandColor: "#bf5700", city: "Austin", state: "TX", conference: "SEC", region: "South", scorecardId: 228778, wikiTitle: "University of Texas at Austin", domain: "utexas.edu", lat: 30.2828, lng: -97.7383, approxEnrollment: 52000, approxAcceptRate: 29 },
  { id: "tamu", name: "Texas A&M University", shortName: "Texas A&M", abbr: "TAMU", brandColor: "#500000", city: "College Station", state: "TX", conference: "SEC", region: "South", scorecardId: 228723, wikiTitle: "Texas A&M University", domain: "tamu.edu", lat: 30.6187, lng: -96.3365, approxEnrollment: 72000, approxAcceptRate: 63 },
  { id: "smu", name: "Southern Methodist University", shortName: "SMU", abbr: "SMU", brandColor: "#0033A0", city: "Dallas", state: "TX", conference: "ACC", region: "South", scorecardId: 228459, wikiTitle: "Southern Methodist University", domain: "smu.edu", lat: 32.8412, lng: -96.7852, approxEnrollment: 12000, approxAcceptRate: 49 },
  // Virginia
  { id: "virginia", name: "University of Virginia", shortName: "Virginia", abbr: "UVA", brandColor: "#232D4B", city: "Charlottesville", state: "VA", conference: "ACC", region: "South", scorecardId: 234076, wikiTitle: "University of Virginia", domain: "virginia.edu", lat: 38.0336, lng: -78.5080, approxEnrollment: 26000, approxAcceptRate: 19 },
  { id: "vatech", name: "Virginia Tech", shortName: "Virginia Tech", abbr: "VT", brandColor: "#630031", city: "Blacksburg", state: "VA", conference: "ACC", region: "South", scorecardId: 233921, wikiTitle: "Virginia Tech", domain: "vt.edu", lat: 37.2296, lng: -80.4139, approxEnrollment: 37000, approxAcceptRate: 57 },
  // West Virginia
  { id: "wvu", name: "West Virginia University", shortName: "West Virginia", abbr: "WVU", brandColor: "#002855", city: "Morgantown", state: "WV", conference: "Big 12", region: "South", scorecardId: 237011, wikiTitle: "West Virginia University", domain: "wvu.edu", lat: 39.6355, lng: -79.9545, approxEnrollment: 26000, approxAcceptRate: 88 },
  { id: "marshall", name: "Marshall University", shortName: "Marshall", abbr: "MRSH", brandColor: "#00B140", city: "Huntington", state: "WV", conference: "Sun Belt", region: "South", scorecardId: 237525, wikiTitle: "Marshall University", domain: "marshall.edu", lat: 38.4238, lng: -82.4257, approxEnrollment: 12000, approxAcceptRate: 83 },

  // ── WEST (AK, AZ, CA, CO, HI, ID, MT, NM, NV, OR, UT, WA, WY) ──────
  // Alaska
  { id: "alaskafairbanks", name: "University of Alaska Fairbanks", shortName: "Alaska Fairbanks", abbr: "UAF", brandColor: "#236192", city: "Fairbanks", state: "AK", conference: "Independent", region: "West", scorecardId: 102614, wikiTitle: "University of Alaska Fairbanks", domain: "uaf.edu", lat: 64.8591, lng: -147.8481, approxEnrollment: 8000, approxAcceptRate: 72 },
  { id: "alaskaanchorage", name: "University of Alaska Anchorage", shortName: "Alaska Anchorage", abbr: "UAA", brandColor: "#00583D", city: "Anchorage", state: "AK", conference: "Independent", region: "West", scorecardId: 102553, wikiTitle: "University of Alaska Anchorage", domain: "uaa.alaska.edu", lat: 61.1900, lng: -149.8194, approxEnrollment: 13000, approxAcceptRate: 63 },
  // Arizona
  { id: "asu", name: "Arizona State University", shortName: "Arizona State", abbr: "ASU", brandColor: "#8c1d40", city: "Tempe", state: "AZ", conference: "Big 12", region: "West", scorecardId: 104151, wikiTitle: "Arizona State University", domain: "asu.edu", lat: 33.4177, lng: -111.9344, approxEnrollment: 78000, approxAcceptRate: 88 },
  { id: "arizona", name: "University of Arizona", shortName: "Arizona", abbr: "ZONA", brandColor: "#CC0033", city: "Tucson", state: "AZ", conference: "Big 12", region: "West", scorecardId: 104179, wikiTitle: "University of Arizona", domain: "arizona.edu", lat: 32.2319, lng: -110.9501, approxEnrollment: 49000, approxAcceptRate: 87 },
  // California (3 schools — largest state)
  { id: "ucla", name: "University of California, Los Angeles", shortName: "UCLA", abbr: "UCLA", brandColor: "#2774AE", city: "Los Angeles", state: "CA", conference: "Big Ten", region: "West", scorecardId: 110662, wikiTitle: "University of California, Los Angeles", domain: "ucla.edu", lat: 34.0689, lng: -118.4452, approxEnrollment: 47000, approxAcceptRate: 9 },
  { id: "usc", name: "University of Southern California", shortName: "USC", abbr: "USC", brandColor: "#990000", city: "Los Angeles", state: "CA", conference: "Big Ten", region: "West", scorecardId: 123961, wikiTitle: "University of Southern California", domain: "usc.edu", lat: 34.0224, lng: -118.2851, approxEnrollment: 49000, approxAcceptRate: 12 },
  { id: "berkeley", name: "University of California, Berkeley", shortName: "Cal", abbr: "CAL", brandColor: "#003262", city: "Berkeley", state: "CA", conference: "ACC", region: "West", scorecardId: 110635, wikiTitle: "University of California, Berkeley", domain: "berkeley.edu", lat: 37.8719, lng: -122.2585, approxEnrollment: 45000, approxAcceptRate: 11 },
  // Colorado
  { id: "colorado", name: "University of Colorado Boulder", shortName: "Colorado", abbr: "CU", brandColor: "#CFB87C", city: "Boulder", state: "CO", conference: "Big 12", region: "West", scorecardId: 126614, wikiTitle: "University of Colorado Boulder", domain: "colorado.edu", lat: 40.0076, lng: -105.2659, approxEnrollment: 38000, approxAcceptRate: 80 },
  { id: "colostate", name: "Colorado State University", shortName: "Colorado State", abbr: "CSU", brandColor: "#1E4D2B", city: "Fort Collins", state: "CO", conference: "Mountain West", region: "West", scorecardId: 126818, wikiTitle: "Colorado State University", domain: "colostate.edu", lat: 40.5734, lng: -105.0866, approxEnrollment: 34000, approxAcceptRate: 88 },
  // Hawaii
  { id: "hawaii", name: "University of Hawaiʻi at Mānoa", shortName: "Hawaii", abbr: "UH", brandColor: "#024731", city: "Honolulu", state: "HI", conference: "Mountain West", region: "West", scorecardId: 141574, wikiTitle: "University of Hawaii at Manoa", domain: "manoa.hawaii.edu", lat: 21.2969, lng: -157.8171, approxEnrollment: 18000, approxAcceptRate: 85 },
  { id: "hawaiipacific", name: "Hawaiʻi Pacific University", shortName: "Hawaii Pacific", abbr: "HPU", brandColor: "#003DA5", city: "Honolulu", state: "HI", conference: "PacWest", region: "West", scorecardId: 141644, wikiTitle: "Hawaii Pacific University", domain: "hpu.edu", lat: 21.3069, lng: -157.8583, approxEnrollment: 4000, approxAcceptRate: 95 },
  // Idaho
  { id: "boisestate", name: "Boise State University", shortName: "Boise State", abbr: "BSU", brandColor: "#0033A0", city: "Boise", state: "ID", conference: "Mountain West", region: "West", scorecardId: 142115, wikiTitle: "Boise State University", domain: "boisestate.edu", lat: 43.6036, lng: -116.2025, approxEnrollment: 28000, approxAcceptRate: 83 },
  { id: "idaho", name: "University of Idaho", shortName: "Idaho", abbr: "UI", brandColor: "#B5985A", city: "Moscow", state: "ID", conference: "Big Sky", region: "West", scorecardId: 142285, wikiTitle: "University of Idaho", domain: "uidaho.edu", lat: 46.7260, lng: -117.0145, approxEnrollment: 11000, approxAcceptRate: 78 },
  // Montana
  { id: "montana", name: "University of Montana", shortName: "Montana", abbr: "UM", brandColor: "#660033", city: "Missoula", state: "MT", conference: "Big Sky", region: "West", scorecardId: 180461, wikiTitle: "University of Montana", domain: "umt.edu", lat: 46.8625, lng: -113.9850, approxEnrollment: 11000, approxAcceptRate: 93 },
  { id: "montanastate", name: "Montana State University", shortName: "Montana State", abbr: "MSU", brandColor: "#003875", city: "Bozeman", state: "MT", conference: "Big Sky", region: "West", scorecardId: 180489, wikiTitle: "Montana State University", domain: "montana.edu", lat: 45.6673, lng: -111.0496, approxEnrollment: 17000, approxAcceptRate: 85 },
  // New Mexico
  { id: "newmexico", name: "University of New Mexico", shortName: "New Mexico", abbr: "UNM", brandColor: "#BA0C2F", city: "Albuquerque", state: "NM", conference: "Mountain West", region: "West", scorecardId: 187985, wikiTitle: "University of New Mexico", domain: "unm.edu", lat: 35.0845, lng: -106.6196, approxEnrollment: 25000, approxAcceptRate: 96 },
  { id: "nmsu", name: "New Mexico State University", shortName: "NMSU", abbr: "NMSU", brandColor: "#8B0000", city: "Las Cruces", state: "NM", conference: "CUSA", region: "West", scorecardId: 188030, wikiTitle: "New Mexico State University", domain: "nmsu.edu", lat: 32.2817, lng: -106.7471, approxEnrollment: 14000, approxAcceptRate: 58 },
  // Nevada
  { id: "unlv", name: "University of Nevada, Las Vegas", shortName: "UNLV", abbr: "UNLV", brandColor: "#B10202", city: "Las Vegas", state: "NV", conference: "Mountain West", region: "West", scorecardId: 182290, wikiTitle: "University of Nevada, Las Vegas", domain: "unlv.edu", lat: 36.1084, lng: -115.1440, approxEnrollment: 31000, approxAcceptRate: 85 },
  { id: "nevada", name: "University of Nevada, Reno", shortName: "Nevada", abbr: "UNR", brandColor: "#003366", city: "Reno", state: "NV", conference: "Mountain West", region: "West", scorecardId: 182281, wikiTitle: "University of Nevada, Reno", domain: "unr.edu", lat: 39.5434, lng: -119.8157, approxEnrollment: 21000, approxAcceptRate: 88 },
  // Oregon
  { id: "oregon", name: "University of Oregon", shortName: "Oregon", abbr: "UO", brandColor: "#154733", city: "Eugene", state: "OR", conference: "Big Ten", region: "West", scorecardId: 209551, wikiTitle: "University of Oregon", domain: "uoregon.edu", lat: 44.0448, lng: -123.0726, approxEnrollment: 24000, approxAcceptRate: 82 },
  { id: "oregonstate", name: "Oregon State University", shortName: "Oregon State", abbr: "ORST", brandColor: "#DC4405", city: "Corvallis", state: "OR", conference: "Pac-12", region: "West", scorecardId: 209542, wikiTitle: "Oregon State University", domain: "oregonstate.edu", lat: 44.5639, lng: -123.2794, approxEnrollment: 34000, approxAcceptRate: 82 },
  // Utah
  { id: "utah", name: "University of Utah", shortName: "Utah", abbr: "UTAH", brandColor: "#CC0000", city: "Salt Lake City", state: "UT", conference: "Big 12", region: "West", scorecardId: 230764, wikiTitle: "University of Utah", domain: "utah.edu", lat: 40.7649, lng: -111.8421, approxEnrollment: 35000, approxAcceptRate: 90 },
  { id: "byu", name: "Brigham Young University", shortName: "BYU", abbr: "BYU", brandColor: "#002E5D", city: "Provo", state: "UT", conference: "Big 12", region: "West", scorecardId: 230038, wikiTitle: "Brigham Young University", domain: "byu.edu", lat: 40.2519, lng: -111.6493, approxEnrollment: 34000, approxAcceptRate: 67 },
  // Washington
  { id: "washington", name: "University of Washington", shortName: "Washington", abbr: "UW", brandColor: "#4B2E83", city: "Seattle", state: "WA", conference: "Big Ten", region: "West", scorecardId: 236948, wikiTitle: "University of Washington", domain: "uw.edu", lat: 47.6553, lng: -122.3035, approxEnrollment: 49000, approxAcceptRate: 48 },
  { id: "wsu", name: "Washington State University", shortName: "Washington State", abbr: "WSU", brandColor: "#981E32", city: "Pullman", state: "WA", conference: "Pac-12", region: "West", scorecardId: 236939, wikiTitle: "Washington State University", domain: "wsu.edu", lat: 46.7298, lng: -117.1817, approxEnrollment: 29000, approxAcceptRate: 83 },
  // Wyoming
  { id: "wyoming", name: "University of Wyoming", shortName: "Wyoming", abbr: "WYO", brandColor: "#492F24", city: "Laramie", state: "WY", conference: "Mountain West", region: "West", scorecardId: 240727, wikiTitle: "University of Wyoming", domain: "uwyo.edu", lat: 41.3149, lng: -105.5666, approxEnrollment: 12000, approxAcceptRate: 95 },

  // ── NORTHEAST (CT, DE, MA, MD, ME, NH, NJ, NY, PA, RI, VT) ──────────
  // Connecticut
  { id: "uconn", name: "University of Connecticut", shortName: "UConn", abbr: "UCONN", brandColor: "#000E2F", city: "Storrs", state: "CT", conference: "Big East", region: "Northeast", scorecardId: 129020, wikiTitle: "University of Connecticut", domain: "uconn.edu", lat: 41.8077, lng: -72.2540, approxEnrollment: 32000, approxAcceptRate: 56 },
  { id: "yale", name: "Yale University", shortName: "Yale", abbr: "YALE", brandColor: "#00356B", city: "New Haven", state: "CT", conference: "Ivy League", region: "Northeast", scorecardId: 130794, wikiTitle: "Yale University", domain: "yale.edu", lat: 41.3163, lng: -72.9223, approxEnrollment: 14000, approxAcceptRate: 5 },
  // Delaware
  { id: "delaware", name: "University of Delaware", shortName: "Delaware", abbr: "UD", brandColor: "#00539F", city: "Newark", state: "DE", conference: "CAA", region: "Northeast", scorecardId: 130943, wikiTitle: "University of Delaware", domain: "udel.edu", lat: 39.6837, lng: -75.7497, approxEnrollment: 23000, approxAcceptRate: 67 },
  { id: "delawarestate", name: "Delaware State University", shortName: "Delaware State", abbr: "DSU", brandColor: "#C41230", city: "Dover", state: "DE", conference: "MEAC", region: "Northeast", scorecardId: 130934, wikiTitle: "Delaware State University", domain: "desu.edu", lat: 39.1862, lng: -75.5424, approxEnrollment: 5000, approxAcceptRate: 52 },
  // Massachusetts
  { id: "bu", name: "Boston University", shortName: "Boston University", abbr: "BU", brandColor: "#CC0000", city: "Boston", state: "MA", conference: "Patriot League", region: "Northeast", scorecardId: 164988, wikiTitle: "Boston University", domain: "bu.edu", lat: 42.3505, lng: -71.1054, approxEnrollment: 36000, approxAcceptRate: 14 },
  { id: "umass", name: "University of Massachusetts Amherst", shortName: "UMass", abbr: "UMASS", brandColor: "#881C1C", city: "Amherst", state: "MA", conference: "A-10", region: "Northeast", scorecardId: 166629, wikiTitle: "University of Massachusetts Amherst", domain: "umass.edu", lat: 42.3868, lng: -72.5301, approxEnrollment: 32000, approxAcceptRate: 64 },
  // Maryland
  { id: "maryland", name: "University of Maryland, College Park", shortName: "Maryland", abbr: "UMD", brandColor: "#E03A3E", city: "College Park", state: "MD", conference: "Big Ten", region: "Northeast", scorecardId: 163286, wikiTitle: "University of Maryland, College Park", domain: "umd.edu", lat: 38.9869, lng: -76.9426, approxEnrollment: 41000, approxAcceptRate: 44 },
  { id: "towson", name: "Towson University", shortName: "Towson", abbr: "TU", brandColor: "#FFB81C", city: "Towson", state: "MD", conference: "CAA", region: "Northeast", scorecardId: 163268, wikiTitle: "Towson University", domain: "towson.edu", lat: 39.3943, lng: -76.6086, approxEnrollment: 23000, approxAcceptRate: 75 },
  // Maine
  { id: "maine", name: "University of Maine", shortName: "Maine", abbr: "UME", brandColor: "#003263", city: "Orono", state: "ME", conference: "America East", region: "Northeast", scorecardId: 161253, wikiTitle: "University of Maine", domain: "umaine.edu", lat: 44.9006, lng: -68.6721, approxEnrollment: 12000, approxAcceptRate: 93 },
  { id: "usm", name: "University of Southern Maine", shortName: "Southern Maine", abbr: "USM", brandColor: "#003B6F", city: "Portland", state: "ME", conference: "Little East", region: "Northeast", scorecardId: 161554, wikiTitle: "University of Southern Maine", domain: "usm.maine.edu", lat: 43.6561, lng: -70.2810, approxEnrollment: 7000, approxAcceptRate: 89 },
  // New Hampshire
  { id: "newhampshire", name: "University of New Hampshire", shortName: "New Hampshire", abbr: "UNH", brandColor: "#003DA5", city: "Durham", state: "NH", conference: "America East", region: "Northeast", scorecardId: 183044, wikiTitle: "University of New Hampshire", domain: "unh.edu", lat: 43.1347, lng: -70.9311, approxEnrollment: 15000, approxAcceptRate: 78 },
  { id: "dartmouth", name: "Dartmouth College", shortName: "Dartmouth", abbr: "DART", brandColor: "#00693E", city: "Hanover", state: "NH", conference: "Ivy League", region: "Northeast", scorecardId: 182670, wikiTitle: "Dartmouth College", domain: "dartmouth.edu", lat: 43.7044, lng: -72.2887, approxEnrollment: 7000, approxAcceptRate: 6 },
  // New Jersey
  { id: "rutgers", name: "Rutgers University–New Brunswick", shortName: "Rutgers", abbr: "RU", brandColor: "#CC0033", city: "New Brunswick", state: "NJ", conference: "Big Ten", region: "Northeast", scorecardId: 186380, wikiTitle: "Rutgers University", domain: "rutgers.edu", lat: 40.5008, lng: -74.4474, approxEnrollment: 50000, approxAcceptRate: 68 },
  { id: "princeton", name: "Princeton University", shortName: "Princeton", abbr: "PRIN", brandColor: "#FF6F00", city: "Princeton", state: "NJ", conference: "Ivy League", region: "Northeast", scorecardId: 186131, wikiTitle: "Princeton University", domain: "princeton.edu", lat: 40.3440, lng: -74.6514, approxEnrollment: 9000, approxAcceptRate: 4 },
  // New York
  { id: "syracuse", name: "Syracuse University", shortName: "Syracuse", abbr: "SYR", brandColor: "#F76900", city: "Syracuse", state: "NY", conference: "ACC", region: "Northeast", scorecardId: 196413, wikiTitle: "Syracuse University", domain: "syracuse.edu", lat: 43.0392, lng: -76.1351, approxEnrollment: 22000, approxAcceptRate: 43 },
  { id: "buffalo", name: "University at Buffalo", shortName: "Buffalo", abbr: "UB", brandColor: "#005BBB", city: "Buffalo", state: "NY", conference: "MAC", region: "Northeast", scorecardId: 196088, wikiTitle: "University at Buffalo", domain: "buffalo.edu", lat: 42.9988, lng: -78.7867, approxEnrollment: 32000, approxAcceptRate: 60 },
  // Pennsylvania
  { id: "pennstate", name: "Pennsylvania State University", shortName: "Penn State", abbr: "PSU", brandColor: "#041E42", city: "State College", state: "PA", conference: "Big Ten", region: "Northeast", scorecardId: 214777, wikiTitle: "Pennsylvania State University", domain: "psu.edu", lat: 40.7982, lng: -77.8599, approxEnrollment: 87000, approxAcceptRate: 54 },
  { id: "pitt", name: "University of Pittsburgh", shortName: "Pitt", abbr: "PITT", brandColor: "#003594", city: "Pittsburgh", state: "PA", conference: "ACC", region: "Northeast", scorecardId: 215293, wikiTitle: "University of Pittsburgh", domain: "pitt.edu", lat: 40.4444, lng: -79.9608, approxEnrollment: 34000, approxAcceptRate: 57 },
  // Rhode Island
  { id: "uri", name: "University of Rhode Island", shortName: "Rhode Island", abbr: "URI", brandColor: "#002147", city: "Kingston", state: "RI", conference: "A-10", region: "Northeast", scorecardId: 217484, wikiTitle: "University of Rhode Island", domain: "uri.edu", lat: 41.4837, lng: -71.5268, approxEnrollment: 17000, approxAcceptRate: 76 },
  { id: "brown", name: "Brown University", shortName: "Brown", abbr: "BROWN", brandColor: "#4E3629", city: "Providence", state: "RI", conference: "Ivy League", region: "Northeast", scorecardId: 217156, wikiTitle: "Brown University", domain: "brown.edu", lat: 41.8268, lng: -71.4025, approxEnrollment: 11000, approxAcceptRate: 5 },
  // Vermont
  { id: "vermont", name: "University of Vermont", shortName: "Vermont", abbr: "UVM", brandColor: "#003300", city: "Burlington", state: "VT", conference: "America East", region: "Northeast", scorecardId: 231174, wikiTitle: "University of Vermont", domain: "uvm.edu", lat: 44.4782, lng: -73.1960, approxEnrollment: 13000, approxAcceptRate: 68 },
  { id: "middlebury", name: "Middlebury College", shortName: "Middlebury", abbr: "MIDD", brandColor: "#003DA5", city: "Middlebury", state: "VT", conference: "NESCAC", region: "Northeast", scorecardId: 231059, wikiTitle: "Middlebury College", domain: "middlebury.edu", lat: 44.0087, lng: -73.1680, approxEnrollment: 3000, approxAcceptRate: 13 },
];

export const uniById = (id: string) => UNIVERSITIES.find((u) => u.id === id);
export const SCORECARD_IDS = UNIVERSITIES.map((u) => u.scorecardId).filter((id) => id > 0).join(",");
